# Generated by Django 6.0.5 on 2026-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Tylko dla pracowników zmianowych - używane do automatycznego dodawania przedstawicieli obszaru podczas inspekcji. Puste pole = pracownik niezmianowy.', max_length=2, null=True, verbose_name='Zmiana'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('WCE', 'WCE - Produkcja'), ('WPP', 'WPP - Pakownia'), ('WLS', 'WLS - Magazyn'), ('WED', 'WED - Dział techniczny'), ('DT', 'DT - Dział techniczny'), ('MIX', 'MIX - obszar mieszany')], help_text='Dział tej osoby (dla ról Pakownia/Produkcja, Techniczny, Logistyka wynika z roli, ale można doprecyzować np. WCE vs WPP).', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='receives_escalations',
            field=models.BooleanField(default=False, help_text='Osoba z tej listy otrzyma powiadomienie, gdy niezgodność jest przeterminowana (eskalacja).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('HELPDESK', 'Helpdesk'), ('AUDYTOR', 'Audytor'), ('PAKOWNIA_PRODUKCJA', 'Pakownia / Produkcja'), ('TECHNICZNY', 'Techniczny'), ('LOGISTYKA', 'Logistyka')], default='AUDYTOR', max_length=20),
        ),
    ]
