# Generated by Django 6.0.5 on 2026-08-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('WCE', 'WCE - Produkcja'), ('WPP', 'WPP - Pakownia'), ('KONF', 'MIX - Konfekcjonowanie'), ('WLS', 'WLS - Magazyn'), ('WED', 'WED - Dział techniczny')], help_text='Dział tej osoby (dla ról Pakownia/Produkcja, Techniczny, Logistyka wynika z roli, ale można doprecyzować np. WCE vs WPP).', max_length=10),
        ),
    ]
