# Generated by Django 6.0.5 on 2026-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'QualityAdmin'), ('HELPDESK', 'Helpdesk'), ('AUDYTOR', 'Audytor'), ('PAKOWNIA_PRODUKCJA', 'Pakownia / Produkcja'), ('TECHNICZNY', 'Techniczny'), ('LOGISTYKA', 'Logistyka')], default='AUDYTOR', max_length=20),
        ),
    ]
