# Generated by Django 6.0.5 on 2026-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_area_user',
            field=models.BooleanField(default=False, help_text='Osoba z tej listy może zostać przypisana jako odpowiedzialna za niezgodność oraz jako przedstawiciel obszaru podczas inspekcji.', verbose_name='Użytkownik obszaru'),
        ),
    ]
