# Generated by Django 6.0.5 on 2026-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_area_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_area_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'QualityAdmin'), ('HELPDESK', 'Helpdesk'), ('AUDYTOR', 'Audytor'), ('PAKOWNIA_PRODUKCJA', 'Pakownia / Produkcja'), ('TECHNICZNY', 'Techniczny'), ('LOGISTYKA', 'Logistyka'), ('UZYTKOWNIK_OBSZARU', 'Użytkownik obszaru')], default='AUDYTOR', max_length=20),
        ),
    ]
