# Generated by Django 6.0.5 on 2026-08-01 09:55

import audits.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(help_text='Numeracja rzymska, np. I, II, III', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('max_points', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(choices=[('WCE_WPP', 'WCE/WPP - Produkcja i Pakownia'), ('WLS', 'WLS - Magazyn'), ('WED', 'WED - Dział techniczny')], max_length=10)),
                ('name', models.CharField(help_text='np. Inspekcja GMP/GHP - PRODUKCJA/PAKOWNIA', max_length=200)),
                ('document_code', models.CharField(help_text='Numer i wersja dokumentu, np. CD-00004592-3', max_length=50)),
                ('version_note', models.CharField(blank=True, help_text='np. zm. D, 19.03.2026', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['area_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('number', models.CharField(help_text='np. 1, 2, 3', max_length=10)),
                ('name', models.CharField(max_length=400)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='audits.checklistsection')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('number', models.CharField(help_text='np. 1.1, 2.3', max_length=10)),
                ('description', models.TextField()),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audits.checklistsubsection')),
            ],
            options={
                'ordering': ['subsection', 'order'],
            },
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='audits.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/godzina inspekcji')),
                ('area_detail', models.CharField(blank=True, max_length=200, verbose_name='Obszar')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('n/d', 'nie dotyczy')], default='n/d', max_length=5)),
                ('area_representatives', models.CharField(blank=True, help_text='Imiona i nazwiska osób reprezentujących obszar podczas inspekcji', max_length=300, verbose_name='Przedstawiciel(e) obszaru')),
                ('lines_working', models.TextField(blank=True, verbose_name='Linie pracujące')),
                ('lines_not_working_cleaning', models.TextField(blank=True, verbose_name='Linie niepracujące (mycie)')),
                ('lines_not_working_stopped', models.TextField(blank=True, verbose_name='Linie niepracujące (postój)')),
                ('rooms_checked', models.TextField(blank=True, help_text='Jedna pozycja na linię - dla inspekcji WED', verbose_name='Sprawdzone pomieszczenia/miejsca')),
                ('status', models.CharField(choices=[('DRAFT', 'Wersja robocza'), ('SUBMITTED', 'Zakończona'), ('REPORT_SENT', 'Raport wysłany'), ('CLOSED', 'Zamknięta (wszystkie NC zamknięte)')], default='DRAFT', max_length=20)),
                ('summary_good', models.TextField(blank=True, verbose_name='Podsumowanie - co było ok')),
                ('summary_to_fix', models.TextField(blank=True, verbose_name='Podsumowanie - co do poprawki')),
                ('report_recipients', models.CharField(blank=True, help_text='Adresy e-mail rozdzielone przecinkiem', max_length=500)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections_led', to=settings.AUTH_USER_MODEL, verbose_name='Osoba przeprowadzająca inspekcję')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='audits.checklisttemplate')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('inspection_date', models.DateField(verbose_name='Data inspekcji')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Data wpisu do rejestru')),
                ('department', models.CharField(choices=[('WCE', 'WCE - Produkcja'), ('WPP', 'WPP - Pakownia'), ('WLS', 'WLS - Magazyn'), ('WED', 'WED - Dział techniczny'), ('DT', 'DT - Dział techniczny'), ('MIX', 'MIX - obszar mieszany')], max_length=10, verbose_name='Obszar')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('n/d', 'nie dotyczy')], default='n/d', max_length=5)),
                ('area_representative', models.CharField(blank=True, max_length=300, verbose_name='Przedstawiciel obszaru')),
                ('gmp_category', models.CharField(blank=True, max_length=200, verbose_name='Obszar GMP/GHP')),
                ('checklist_point_label', models.CharField(blank=True, help_text="np. 1.1, 3.4 lub 'brak punktu'", max_length=30, verbose_name='Punkt checklisty')),
                ('point_description', models.CharField(blank=True, max_length=400, verbose_name='Opis punktu')),
                ('location_detail', models.CharField(blank=True, max_length=200, verbose_name='Obszar / lokalizacja')),
                ('description', models.TextField(verbose_name='Opis niezgodności')),
                ('root_cause', models.TextField(blank=True, verbose_name='Źródło problemu')),
                ('corrective_action', models.TextField(blank=True, verbose_name='Działania korekcyjne')),
                ('corrective_action_date', models.DateField(blank=True, null=True, verbose_name='Data podjęcia działań korekcyjnych')),
                ('preventive_action', models.TextField(blank=True, verbose_name='Działania korygujące')),
                ('planned_preventive_date', models.DateField(blank=True, null=True, verbose_name='Planowana data wprowadzenia działań korygujących')),
                ('actual_preventive_date', models.DateField(blank=True, null=True, verbose_name='Faktyczna data wprowadzenia działań korygujących')),
                ('status', models.CharField(choices=[('W_TOKU', 'W toku'), ('WDROZONE', 'Wdrożone'), ('ANULOWANE', 'Anulowane')], default='W_TOKU', max_length=10, verbose_name='Status działań')),
                ('auditor_comment', models.TextField(blank=True, verbose_name='Uwagi audytora / inne')),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='audits.checklistitem')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonconformities', to='audits.inspection')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformities_raised', to=settings.AUTH_USER_MODEL, verbose_name='Osoba przeprowadzająca inspekcję')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='Osoba odpowiedzialna za obszar')),
            ],
            options={
                'verbose_name': 'Niezgodność',
                'verbose_name_plural': 'Niezgodności',
                'ordering': ['-inspection_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NonConformityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=audits.models.nc_photo_path)),
                ('kind', models.CharField(choices=[('NIEZGODNOSC', 'Zdjęcie niezgodności'), ('DOWOD', 'Dowód podjętych działań')], default='NIEZGODNOSC', max_length=15)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='audits.nonconformity')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('OK', 'Zgodność'), ('NC', 'Niezgodność'), ('NA', 'Nie dotyczy')], default='OK', max_length=5)),
                ('note', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='audits.inspection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.checklistitem')),
            ],
            options={
                'ordering': ['item__subsection__section__order', 'item__subsection__order', 'item__order'],
                'unique_together': {('inspection', 'item')},
            },
        ),
        migrations.CreateModel(
            name='InspectionSectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_results', to='audits.inspection')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.checklistsection')),
            ],
            options={
                'ordering': ['section__order'],
                'unique_together': {('inspection', 'section')},
            },
        ),
    ]
