# Generated by Django 6.0.5 on 2026-08-06 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformity',
            name='is_extra',
            field=models.BooleanField(default=False, help_text='Dodana ponad standardowe zaznaczenie punktu checklisty - odlicza punkt od ogólnej puli wyniku inspekcji, a nie od konkretnej sekcji.', verbose_name='Niezgodność dodatkowa'),
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='area_representatives',
        ),
        migrations.AddField(
            model_name='inspection',
            name='area_representatives',
            field=models.ManyToManyField(blank=True, help_text='Domyślnie osoby z wybranej zmiany - lista może być modyfikowana przed zapisem inspekcji.', related_name='represented_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Przedstawiciele obszaru'),
        ),
    ]
