# Generated by Django 6.0.5 on 2026-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_nonconformity_is_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformity',
            name='checklist_point_label',
            field=models.CharField(blank=True, help_text="np. 1.1, 3.4 lub 'Brak punktu odniesienia'", max_length=30, verbose_name='Punkt checklisty'),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='department',
            field=models.CharField(choices=[('WCE', 'WCE - Produkcja'), ('WPP', 'WPP - Pakownia'), ('KONF', 'MIX - Konfekcjonowanie'), ('WLS', 'WLS - Magazyn'), ('WED', 'WED - Dział techniczny')], max_length=10, verbose_name='Obszar'),
        ),
    ]
