# Generated by Django 6.0.5 on 2026-08-28 11:23

from django.db import migrations


def relabel_forward(apps, schema_editor):
    NonConformity = apps.get_model("audits", "NonConformity")
    NonConformity.objects.filter(checklist_point_label="brak punktu").update(
        checklist_point_label="Brak punktu odniesienia"
    )


def relabel_backward(apps, schema_editor):
    NonConformity = apps.get_model("audits", "NonConformity")
    NonConformity.objects.filter(checklist_point_label="Brak punktu odniesienia").update(
        checklist_point_label="brak punktu"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_nonconformity_checklist_point_label_and_more'),
    ]

    operations = [
        migrations.RunPython(relabel_forward, relabel_backward),
    ]
