# Generated by Django 6.0.5 on 2026-08-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_backfill_brak_punktu_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Komentarz'),
        ),
    ]
