# Generated by Django 6.0.5 on 2026-09-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_inspection_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Ukryta inspekcja znika z rejestru inspekcji dla wszystkich oprócz QualityAdmin/Helpdesku (nadal dostępna pod bezpośrednim linkiem).', verbose_name='Ukryta'),
        ),
    ]
