"""
Django settings for audytgmp project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Na Azure ustaw SECRET_KEY jako zmienną środowiskową (App Service -> Environment variables).
# Poniższa wartość jest bezpieczna WYŁĄCZNIE do pracy lokalnej/deweloperskiej.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-3x90!69zif^mc*n243swzr)wyvcfel7)i0kfi)$zlir4ce&(iw',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Ustaw DEBUG=False jako zmienną środowiskową na Azure.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# WEBSITE_HOSTNAME jest ustawiane automatycznie przez Azure App Service
# (np. audyty-gmp-ghp.azurewebsites.net) - dodajemy je do dozwolonych hostów.
_azure_hostname = os.environ.get('WEBSITE_HOSTNAME')
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']
if _azure_hostname:
    ALLOWED_HOSTS.append(_azure_hostname)
_extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = []
if _azure_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_azure_hostname}')
_extra_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if _extra_csrf_origins:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_csrf_origins.split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'audits',
]

AUTH_USER_MODEL = 'accounts.User'

# Logowanie: numer chipa (username) + 6-znakowy kod autoryzujący (password).
# Cała logika dwuetapowego logowania (ustawienie kodu przy pierwszym logowaniu,
# weryfikacja przy kolejnych) żyje w accounts/views.py::chip_login i korzysta
# ze standardowego ModelBackend (username+password) - nie potrzeba custom backendu.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'audytgmp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'audytgmp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Lokalnie (bez DATABASE_URL): SQLite, zero konfiguracji.
# Na Azure: DATABASE_URL wskazuje na PostgreSQL, np.
#   postgres://uzytkownik:haslo@nazwa-serwera.postgres.database.azure.com:5432/nazwa_bazy?sslmode=require

_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Media files (zdjęcia z inspekcji, dowody działań korygujących).
# UWAGA: na Azure App Service (Linux) system plików nie jest trwały poza
# katalogiem /home - dlatego tam trzymamy media/, żeby przetrwały restart /
# redeploy. To rozwiązanie tymczasowe; docelowo warto przenieść na Azure Blob
# Storage (django-storages) dla trwałości i skalowalności.
if os.environ.get('WEBSITE_HOSTNAME'):
    MEDIA_ROOT = Path('/home/media')
else:
    MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'chip_login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'chip_login'

# E-mail: w środowisku deweloperskim wiadomości (przypomnienia, eskalacje)
# trafiają do konsoli. W produkcji podłączyć prawdziwy backend SMTP Brüggen.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'audyty-gmp-ghp@brueggen.com'

# Liczba dni na uzupełnienie działań przez osobę odpowiedzialną, po której
# wysyłane jest przypomnienie; kolejny próg (patrz management command)
# uruchamia eskalację do dyrekcji.
NC_REMINDER_AFTER_DAYS = 7
NC_ESCALATION_AFTER_DAYS = 14

# Podpowiedzi opisu niezgodności (Azure OpenAI, GPT-4o) - opcjonalne.
# Ustaw jako zmienne środowiskowe; jeśli puste, funkcja jest po prostu
# niedostępna w UI (patrz audits/ai.py).
AZURE_OPENAI_ENDPOINT = os.environ.get('AZURE_OPENAI_ENDPOINT', '')
AZURE_OPENAI_KEY = os.environ.get('AZURE_OPENAI_KEY', '')
AZURE_OPENAI_DEPLOYMENT = os.environ.get('AZURE_OPENAI_DEPLOYMENT', '')
AZURE_OPENAI_API_VERSION = os.environ.get('AZURE_OPENAI_API_VERSION', '2024-08-01-preview')

# Wysyłka raportu z załącznikiem PDF (Azure Communication Services Email) -
# opcjonalne, tak jak Azure OpenAI powyżej. Jeśli puste, wysyłka raportu po
# prostu się nie powiedzie z czytelnym komunikatem (patrz audits/email_acs.py) -
# reszta aplikacji działa normalnie.
# AZURE_CONNECTION_STRING - dokładnie ta nazwa zmiennej jest już ustawiona
# w Azure App Service (zasób Communication Services).
AZURE_COMMUNICATION_CONNECTION_STRING = os.environ.get('AZURE_CONNECTION_STRING', '')
# Zweryfikowany adres nadawcy w domenie zasobu Communication Services
# (Portal Azure -> zasób Communication Services -> Email -> Domains).
EMAIL_SENDER_ADDRESS = os.environ.get('EMAIL_SENDER_ADDRESS', '')

# Zabezpieczenia produkcyjne - aktywne tylko, gdy DEBUG=False (czyli na Azure,
# zakładając że tam ustawiono DEBUG=False jako zmienną środowiskową).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
